// GENERATED by image_processing/tubityx_logo/bake_font.py - do not edit by hand.
// Metrics for Resources/UI/Tex_TubityXFont, the SDF atlas of the TubityX face.

namespace TubityWAI
{
    public static class TubityXFontMetrics
    {
        /// <summary>Cap height the atlas was baked at, in atlas pixels.</summary>
        public const float Cap = 56f;
        /// <summary>Padding around every glyph, in atlas pixels. The quad is
        /// inflated by this so the distance field is not clipped.</summary>
        public const float Pad = 11f;
        /// <summary>SDF half-range in atlas pixels.</summary>
        public const float Spread = 10.0f;
        public const int AtlasWidth = 512;
        public const int AtlasHeight = 624;

        public struct G
        {
            public readonly char Ch;
            public readonly float X, Y, W, H;   // tile rect in atlas pixels, padding included
            public readonly float Advance;      // glyph width in atlas pixels, padding excluded

            public G(char ch, float x, float y, float w, float h, float advance)
            {
                Ch = ch; X = x; Y = y; W = w; H = h; Advance = advance;
            }
        }

        public static readonly G[] Glyphs =
        {
            new G('A', 0, 0, 85, 78, 63.8400f),
            new G('B', 85, 0, 83, 78, 61.0400f),
            new G('C', 168, 0, 83, 78, 61.6000f),
            new G('D', 251, 0, 83, 78, 61.6000f),
            new G('E', 334, 0, 79, 78, 57.1200f),
            new G('F', 413, 0, 78, 78, 56.0000f),
            new G('G', 0, 78, 85, 78, 63.8400f),
            new G('H', 85, 78, 84, 78, 62.7200f),
            new G('I', 169, 78, 38, 78, 15.9040f),
            new G('J', 207, 78, 77, 78, 54.8800f),
            new G('K', 284, 78, 83, 78, 61.6000f),
            new G('L', 367, 78, 77, 78, 54.8800f),
            new G('M', 0, 156, 97, 78, 75.0400f),
            new G('N', 97, 156, 85, 78, 63.8400f),
            new G('O', 182, 156, 87, 78, 64.9600f),
            new G('P', 269, 156, 81, 78, 59.3600f),
            new G('Q', 350, 156, 87, 78, 64.9600f),
            new G('R', 0, 234, 82, 78, 60.4800f),
            new G('S', 82, 234, 81, 78, 59.3600f),
            new G('T', 163, 234, 84, 78, 62.1600f),
            new G('U', 247, 234, 85, 78, 63.0000f),
            new G('V', 332, 234, 85, 78, 63.8400f),
            new G('W', 0, 312, 103, 78, 81.7600f),
            new G('X', 103, 312, 85, 78, 63.8400f),
            new G('Y', 188, 312, 89, 78, 67.2000f),
            new G('Z', 277, 312, 81, 78, 59.3600f),
            new G('0', 358, 312, 85, 78, 63.8400f),
            new G('1', 443, 312, 63, 78, 41.4400f),
            new G('2', 0, 390, 81, 78, 59.3600f),
            new G('3', 81, 390, 81, 78, 59.3600f),
            new G('4', 162, 390, 85, 78, 63.8400f),
            new G('5', 247, 390, 81, 78, 59.3600f),
            new G('6', 328, 390, 83, 78, 61.6000f),
            new G('7', 411, 390, 79, 78, 57.1200f),
            new G('8', 0, 468, 82, 78, 60.4800f),
            new G('9', 82, 468, 83, 78, 61.6000f),
            new G(' ', 165, 468, 48, 78, 25.7600f),
            new G('+', 213, 468, 73, 78, 51.5200f),
            new G('-', 286, 468, 62, 78, 40.3200f),
            new G('.', 348, 468, 41, 78, 19.0400f),
            new G(',', 389, 468, 41, 78, 19.0400f),
            new G(':', 430, 468, 41, 78, 19.0400f),
            new G('!', 471, 468, 38, 78, 16.8000f),
            new G('?', 0, 546, 75, 78, 53.7600f),
            new G('\'', 75, 546, 38, 78, 16.8000f),
            new G('/', 113, 546, 70, 78, 48.1600f),
            new G('(', 183, 546, 51, 78, 29.1200f),
            new G(')', 234, 546, 51, 78, 29.1200f),
            new G('&', 285, 546, 87, 78, 64.9600f),
        };

        private static System.Collections.Generic.Dictionary<char, G> lookup;

        /// <summary>Metrics for one character; falls back to space.</summary>
        public static G Get(char c)
        {
            if (lookup == null)
            {
                lookup = new System.Collections.Generic.Dictionary<char, G>(Glyphs.Length);
                foreach (G g in Glyphs) lookup[g.Ch] = g;
            }
            G found;
            if (lookup.TryGetValue(char.ToUpperInvariant(c), out found)) return found;
            return lookup[' '];
        }
    }
}
