// GENERATED by image_processing/tubityx_logo/export_bands.py - do not edit by hand.
// The bands of the attract-mode hero sphere: latitude rings wound around a
// tilted axis, plus a sparser crossing family. Baked rather than re-rolled at
// runtime so the game matches the art that was signed off.

using UnityEngine;

namespace TubityWAI
{
    public static class NeonBandData
    {
        public struct Band
        {
            public readonly float Theta;    // latitude on the sphere, radians
            public readonly float Width;    // ribbon half-width, fraction of radius
            public readonly Color Colour;
            public readonly int Family;     // 0 = main winding, 1 = crossing

            public Band(float theta, float width, Color colour, int family)
            {
                Theta = theta; Width = width; Colour = colour; Family = family;
            }
        }

        public static readonly Vector3 AxisMain = new Vector3(0.48515f, 0.61566f, -0.62096f);
        public static readonly Vector3 AxisCross = new Vector3(0.85480f, 0.43837f, -0.27774f);

        /// <summary>Ribbons sit just proud of the surface so they never z-fight the core.</summary>
        public const float Lift = 1.0120f;
        /// <summary>Samples around a full ring at the equator; shorter rings use fewer.</summary>
        public const int Segments = 128;
        public static readonly Color CoreColour = new Color(0.0200f, 0.0220f, 0.0550f);

        public static readonly Band[] Bands =
        {
            new Band(0.10000f, 0.02014f, new Color(0.0000f, 0.9500f, 1.0000f), 0),
            new Band(0.64145f, 0.01358f, new Color(0.0182f, 0.8591f, 1.0000f), 0),
            new Band(0.79788f, 0.01757f, new Color(0.0364f, 0.7682f, 1.0000f), 0),
            new Band(0.96809f, 0.01453f, new Color(0.0545f, 0.6773f, 1.0000f), 0),
            new Band(1.21158f, 0.03721f, new Color(1.0000f, 0.7000f, 0.1800f), 0),
            new Band(1.31122f, 0.01908f, new Color(0.0909f, 0.4955f, 1.0000f), 0),
            new Band(1.42287f, 0.01261f, new Color(0.1273f, 0.4227f, 1.0000f), 0),
            new Band(1.49666f, 0.02513f, new Color(0.1818f, 0.3682f, 1.0000f), 0),
            new Band(1.64362f, 0.02970f, new Color(0.2364f, 0.3136f, 1.0000f), 0),
            new Band(1.70882f, 0.02328f, new Color(1.0000f, 0.7000f, 0.1800f), 0),
            new Band(1.82065f, 0.03243f, new Color(0.3455f, 0.2045f, 1.0000f), 0),
            new Band(1.90948f, 0.01976f, new Color(0.4000f, 0.1500f, 1.0000f), 0),
            new Band(2.03257f, 0.02813f, new Color(0.4691f, 0.1409f, 1.0000f), 0),
            new Band(2.14982f, 0.01044f, new Color(0.5382f, 0.1318f, 1.0000f), 0),
            new Band(2.27535f, 0.01977f, new Color(1.0000f, 0.7000f, 0.1800f), 0),
            new Band(2.36174f, 0.01579f, new Color(0.6764f, 0.1136f, 1.0000f), 0),
            new Band(2.44912f, 0.01615f, new Color(0.7455f, 0.1045f, 1.0000f), 0),
            new Band(2.55553f, 0.03785f, new Color(0.8000f, 0.0982f, 0.9745f), 0),
            new Band(2.64986f, 0.03457f, new Color(0.8400f, 0.0945f, 0.9236f), 0),
            new Band(2.76409f, 0.03558f, new Color(1.0000f, 0.7000f, 0.1800f), 0),
            new Band(2.83872f, 0.03192f, new Color(0.9200f, 0.0873f, 0.8218f), 0),
            new Band(2.95952f, 0.01386f, new Color(0.9600f, 0.0836f, 0.7709f), 0),
            new Band(3.04159f, 0.03222f, new Color(1.0000f, 0.0800f, 0.7200f), 0),
            new Band(0.70000f, 0.01830f, new Color(0.0000f, 0.9500f, 1.0000f), 1),
            new Band(1.28053f, 0.02553f, new Color(1.0000f, 0.0800f, 0.7200f), 1),
            new Band(1.86106f, 0.02439f, new Color(0.1000f, 0.4500f, 1.0000f), 1),
            new Band(2.44159f, 0.01546f, new Color(1.0000f, 0.7000f, 0.1800f), 1),
        };
    }
}
