"""Bake the TubityX display face into one SDF atlas + generated C# metrics.

Output:
    Tex_TubityXFont.png        greyscale, R = signed distance (0.5 = glyph edge)
    TubityXFontMetrics.cs      generated lookup table, no runtime parsing
"""
import numpy as np
from PIL import Image
from scipy import ndimage
from glyphs_ext import draw_glyph, WIDTHS, DESC

CAP    = 56          # cap height in atlas pixels
PAD    = 11          # padding around each glyph (must be >= SPREAD)
SPREAD = 10.0        # SDF half-range in atlas pixels
SS     = 4
ATLAS_W = 1024   # keep both dimensions <= 1024 so maxTextureSize never downscales the field

CHARS = ("ABCDEFGHIJKLMNOPQRSTUVWXYZ"
         "abcdefghijklmnopqrstuvwxyz"
         "0123456789"
         " +-.,:!?'/()&$%*=#"
         "\u25C0\u25B6\u25B2\u25BC\u2715\u2713\u2699"
         "\u25A6\u25A4\u25A8\u25A9\u2B55\u2B22\u2726\u2727\u2736\u2389")


BOX = CAP * (1.0 + DESC)      # cap line down to the descender depth


def glyph_sdf(ch):
    """SDF tile for one glyph, padded by PAD on every side. Every tile spans the
    same vertical box - cap line to descender - so the label component can place
    them all from the cap line alone."""
    if ch == " ":
        w = WIDTHS[" "] * CAP
        tile = np.full((int(round(BOX)) + 2 * PAD, int(round(w)) + 2 * PAD), 1.0)
        return tile, w

    g, gw = draw_glyph(ch, CAP * SS)
    tw = int(round(gw)) + 2 * PAD * SS
    th = g.height - 2 + 2 * PAD * SS
    canvas = Image.new("L", (tw, th), 0)
    canvas.paste(g, (PAD * SS, PAD * SS), g)
    mask = np.array(canvas) > 127

    d_out = ndimage.distance_transform_edt(~mask)
    d_in = ndimage.distance_transform_edt(mask)
    d = (d_out - d_in) / SS
    d = np.clip(d, -SPREAD, SPREAD)
    oh, ow = th // SS, tw // SS
    d = d[:oh * SS, :ow * SS].reshape(oh, SS, ow, SS).mean(axis=(1, 3))
    return d / SPREAD * 0.5 + 0.5, gw / SS


tiles = []
for ch in CHARS:
    t, adv = glyph_sdf(ch)
    tiles.append((ch, t, adv))

# ---- shelf pack ---------------------------------------------------------
placed, x, y, shelf_h = [], 0, 0, 0
for ch, t, adv in tiles:
    h, w = t.shape
    if x + w > ATLAS_W:
        x, y, shelf_h = 0, y + shelf_h, 0
    placed.append((ch, t, adv, x, y))
    x += w
    shelf_h = max(shelf_h, h)
atlas_h = y + shelf_h
atlas_h = (atlas_h + 3) // 4 * 4                      # keep it block-friendly

atlas = np.full((atlas_h, ATLAS_W), 1.0)              # 1.0 == fully outside
for ch, t, adv, px, py in placed:
    h, w = t.shape
    atlas[py:py + h, px:px + w] = t

Image.fromarray((np.clip(atlas, 0, 1) * 255 + 0.5).astype(np.uint8), "L") \
     .save("/home/claude/tubityx/Tex_TubityXFont.png")
print("atlas %d x %d, %d glyphs" % (ATLAS_W, atlas_h, len(placed)))

# ---- generated C# -------------------------------------------------------
rows = []
for ch, t, adv, px, py in placed:
    h, w = t.shape
    if ch == "'":
        lit = "'\\''"
    elif ord(ch) > 127:
        lit = "'\\u%04X'" % ord(ch)
    else:
        lit = "'%s'" % ch
    rows.append("            new G(%s, %d, %d, %d, %d, %.4ff)," % (lit, px, py, w, h, adv))

cs = '''// GENERATED by image_processing/tubityx_logo/bake_font.py - do not edit by hand.
// Metrics for Resources/UI/Tex_TubityXFont, the SDF atlas of the TubityX face.

namespace TubityWAI
{
    public static class TubityXFontMetrics
    {
        /// <summary>Cap height the atlas was baked at, in atlas pixels.</summary>
        public const float Cap = %df;
        /// <summary>Padding around every glyph, in atlas pixels. The quad is
        /// inflated by this so the distance field is not clipped.</summary>
        public const float Pad = %df;
        /// <summary>SDF half-range in atlas pixels.</summary>
        public const float Spread = %.1ff;
        public const int AtlasWidth = %d;
        public const int AtlasHeight = %d;

        public struct G
        {
            public readonly char Ch;
            public readonly float X, Y, W, H;   // tile rect in atlas pixels, padding included
            public readonly float Advance;      // glyph width in atlas pixels, padding excluded

            public G(char ch, float x, float y, float w, float h, float advance)
            {
                Ch = ch; X = x; Y = y; W = w; H = h; Advance = advance;
            }
        }

        public static readonly G[] Glyphs =
        {
%s
        };

        private static System.Collections.Generic.Dictionary<char, G> lookup;

        /// <summary>Metrics for one character; falls back to space.</summary>
        public static G Get(char c)
        {
            if (lookup == null)
            {
                lookup = new System.Collections.Generic.Dictionary<char, G>(Glyphs.Length);
                foreach (G g in Glyphs) lookup[g.Ch] = g;
            }
            G found;
            if (lookup.TryGetValue(char.ToUpperInvariant(c), out found)) return found;
            return lookup[' '];
        }
    }
}
''' % (CAP, PAD, SPREAD, ATLAS_W, atlas_h, "\n".join(rows))

open("/home/claude/tubityx/TubityXFontMetrics.cs", "w").write(cs)
print("wrote TubityXFontMetrics.cs")
