"""Emit the band table as C#. Baking the numbers rather than re-deriving them
from an RNG in C# means Unity renders exactly what the offline preview showed."""
import numpy as np
from arcsphere import CFG, PALETTE, GOLD, CORE, _axis

c = CFG
rng = np.random.default_rng(c["seed"])
steps = rng.uniform(1.0 - c["gap_jitter"], 1.0 + c["gap_jitter"], c["bands"])
acc = np.cumsum(steps)
lat = (acc - acc[0]) / (acc[-1] - acc[0])
lat = lat ** c["pole_bias"]
thetas = 0.10 + lat * (np.pi - 0.20)

rows = []
for i in range(c["bands"]):
    w = rng.uniform(c["width_min"], c["width_max"])
    if c["gold_every"] > 0 and i % c["gold_every"] == c["gold_every"] - 1:
        col = np.array(GOLD)
    else:
        f = (i / max(1, c["bands"] - 1)) * (len(PALETTE) - 1)
        k = int(np.floor(f)); fr = f - k
        col = np.array(PALETTE[k]) * (1 - fr) + np.array(PALETTE[min(k + 1, len(PALETTE) - 1)]) * fr
    rows.append((thetas[i], w, col, 0))

ct = np.linspace(0.7, np.pi - 0.7, c["cross_bands"])
cw = rng.uniform(c["width_min"], c["width_max"] * 0.7, c["cross_bands"])
cc = [PALETTE[0], PALETTE[4], PALETTE[1], GOLD][:c["cross_bands"]]
for i in range(c["cross_bands"]):
    rows.append((ct[i], cw[i], np.array(cc[i]), 1))

am = _axis(c["axis_tilt"], c["axis_spin"])
ax = _axis(c["cross_tilt"], c["cross_spin"])
v3 = lambda v: "new Vector3(%.5ff, %.5ff, %.5ff)" % tuple(v)
body = "\n".join(
    "            new Band(%.5ff, %.5ff, new Color(%.4ff, %.4ff, %.4ff), %d)," %
    (t, w, col[0], col[1], col[2], fam) for t, w, col, fam in rows)

cs = '''// GENERATED by image_processing/tubityx_logo/export_bands.py - do not edit by hand.
// The bands of the attract-mode hero sphere: latitude rings wound around a
// tilted axis, plus a sparser crossing family. Baked rather than re-rolled at
// runtime so the game matches the art that was signed off.

using UnityEngine;

namespace TubityWAI
{
    public static class NeonBandData
    {
        public struct Band
        {
            public readonly float Theta;    // latitude on the sphere, radians
            public readonly float Width;    // ribbon half-width, fraction of radius
            public readonly Color Colour;
            public readonly int Family;     // 0 = main winding, 1 = crossing

            public Band(float theta, float width, Color colour, int family)
            {
                Theta = theta; Width = width; Colour = colour; Family = family;
            }
        }

        public static readonly Vector3 AxisMain = %s;
        public static readonly Vector3 AxisCross = %s;

        /// <summary>Ribbons sit just proud of the surface so they never z-fight the core.</summary>
        public const float Lift = %.4ff;
        /// <summary>Samples around a full ring at the equator; shorter rings use fewer.</summary>
        public const int Segments = %d;
        public static readonly Color CoreColour = new Color(%.4ff, %.4ff, %.4ff);

        public static readonly Band[] Bands =
        {
%s
        };
    }
}
''' % (v3(am), v3(ax), c["lift"], c["segments"], CORE[0], CORE[1], CORE[2], body)
open("/home/claude/tubityx/NeonBandData.cs", "w").write(cs)
print("bands:", len(rows), "| axis main", np.round(am, 3), "| cross", np.round(ax, 3))
